version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
  app:
    build: .
    container_name: meal_planner
    depends_on:
      - db
    ports:
      - "8888:8888"
    